### ISSUE TITLE
live scraper page is broken

### ISSUE THREAD

**Issue by skliarie** [nilesr/vichan-ipfs-scraper#1]
live scraper page is broken - shows blank screen.
Additionally, attempt to retrieve the IPFS has returns this error:
$ ipfs get TXkgY29tcHV0ZXIFEAZwY70Eb7Oz0Ukx5eNu5aAHAxEnrw
Error: invalid 'ipfs ref' path

(using ipfs 0.4.16)

**Comment by nilesr** [comment]
Looks like the syntax highlighting is broken ![](http://0x0.st/sO9O.png)

It also looks like nobody's posted an IPFS hash in a while. I can also see that it still links to gitla.in which is dead, and the copyright string is from 2016.
